test:
  dialect: mysql
  datasource: root:root@tcp(0.0.0.0:3307)/test?parseTime=true
  dir: migrations
  table: migrations

development:
  dialect: mysql
  datasource: root:root@tcp(0.0.0.0:3307)/root?parseTime=true
  dir: migrations
  table: migrations

homologation:
  dialect: mysql
  datasource: host=$HLG_DB_HOST user=$HLG_DB_USER password=$HLG_DB_PASSWORD dbname=$HLG_DB_DBNAME sslmode=disable
  dir: migrations
  table: migrations

production:
  dialect: mysql
  datasource: host=$PRD_DB_HOST port=3306 user=$PRD_DB_USER password=$PRD_DB_PASSWORD dbname=$PRD_DB_DBNAME sslmode=disable
  dir: migrations
  table: migrations
